### ISSUE TITLE
UK Met FSOI Data Processing

### ISSUE THREAD

**Issue by hahnd** [JCSDA/FSOI#106]
- [x] Update code to process raw UK Met FSOI data into FSOI formats, bulk, accumbulk, and groupbulk statistics files
 - [x] Update config file with any unknown platforms
 - [x] Check with Met Office to make sure files are not corrupted
 - [x] Update and test FSOI docker image to ingest (download AND process) UK Met data
 - [x] Update CloudFormation to add a scheduled call to ingest UK Met data

**Comment by hahnd** [comment]
@fcvdb I got the 2020 April UKMet data processed over the weekend.  Here is a list of the unknown platform IDs that it found:
instyp: 22501; schar: GOES 271  1                        
instyp: 22502; schar: GOES 271  1                        
instyp: 22511; schar: GOES 271  1                        
instyp: 23613; schar: MSG   5  1                         
instyp: 26330; schar: GOES16 ABICLR ABI

**Comment by hahnd** [comment]
@fcvdb The majority of the UK Met files do not unzip properly.  I have already updated the code to deal with this, but maybe we should check with the Met Office to make sure these files are not accidentally truncated.

notsure:hahnd:/tmp> gunzip 20200415T0000Z.FSO.gz 
gunzip: 20200415T0000Z.FSO.gz: unexpected end of file
gunzip: 20200415T0000Z.FSO.gz: uncompress failed

**Comment by fcvdb** [comment]
UK Met Office FSOI are available from the IOS interface from January 2020. Monthly data are pulled on the 6th of the month.
