### ISSUE TITLE
Mixed HTTP/HTTPS Content

### ISSUE THREAD

**Issue by hahnd** [JCSDA/FSOI#120]
Chrome browser recently complains about mixed HTTP/HTTPS content and the page does not work in Chrome.  The system should be modified to serve FSOI images via HTTPS.

- [ ] Create new SSL Certificate and CloudFront Distribution with the fsoi-image-cache S3 bucket as the origin
- [ ] Create new Route53 entry for fsoi-images.jcsda.org to point to the new CloudFront distribution
- [ ] Update Python code to change image URLs in the websocket response

**Comment by fcvdb** [comment]
This issue was resolved with completion of issue #124
