### ISSUE TITLE
Missing Warning/Error Messages

### ISSUE THREAD

**Issue by hahnd** [JCSDA/FSOI#122]
The warning and error messages are not present in the web application anymore when they are expected to be.  I suspect that this error may have been introduced with the branch: feature/parallel-processing.  The warning and error messages are not persisted to the DynamoDB table.  Doing this may resolve the issue.

**Comment by fcvdb** [comment]
I am closing this issue, as web applications developments are now conducted in the [diag-plots](https://github.com/JCSDA-internal/diag-plots/) repository.
