### ISSUE TITLE
BokehJS Errors with new Time Series plots

### ISSUE THREAD

**Issue by hahnd** [JCSDA/FSOI#123]
The time series plots are causing problems in the web front-end.  The changes on branch feature/tseries4bokeh have caused errors with the web front end.  Need to debug to determine what is happening.

**Comment by fabiolrdiniz** [comment]
This has been fixed with this commit: https://github.com/JCSDA-internal/FSOI/commit/894685f459151da8d7de6e880a8cfd465042c5b5.
