### ISSUE TITLE
Websocket Messages Too Large

### ISSUE THREAD

**Issue by hahnd** [JCSDA/FSOI#124]
Bokeh JSON data is currently passed from the server-side Lambda function to the web browser via the websocket protocol.  After debugging some errors, we found that API Gateway limits websocket payload sizes to 128kB.  The Bokeh JSON data for the new time series plots are > 128kB and we need an alternate solution for passing data from the server-side to the web browser.
https://docs.aws.amazon.com/apigateway/latest/developerguide/limits.html

Option 1:  Instead of sending data through a websocket connection, a URL could be sent instead.  The URL would point to a CloudFront distribution, which would have an S3 origin.  The image and JSON ("data") could be stored in the S3 bucket used as the origin instead of fsoi-image-cache.  This could address Issue #120.  Before doing this, we need to make sure that any new data objects added to the S3 origin would be IMMEDIATELY available through the CloudFront distribution.  If there is a delay, we may want to use an alternative method.

- [x] Update the CloudFormation template to include the S3 bucket, fsoi-image-cache, as an additional CloudFront origin for the ios.jcsda.org domain.  Anything with a /d prefix (for data) will go to the fsoi-image-cache bucket as its origin.
- [x] Update the CloudFormation stack.
- [x] Test that the operational site is still functional.
- [x] Test that we can access the PNG and JSON files in the fsoi-image-cache bucket through https://ios.jcsda.org/d/...
- [x] Update the response message from the Lambda function to include the complete URLs (or can URLs be relative?) to the PNG and JSON files.
- [x] Deploy the Lambda function to AWS.
- [x] Test that the operational site is still functional.
- [x] Update the web application (Angular front-end) to expect the PNG and JSON URLs in the response message and turn off the subsequent requests for JSON data for individual JSON files.
- [x] Test that the PNGs and Bokeh plots still work -- There may be CORS issues with running the web application on the localhost (i.e., using ng serve and http://localhost:4200), which could make testing difficult.  PNGs should appear, but Bokeh plots may not.
- [x] Deploy the web application to the operational system.
- [x] Test that the operational site is still functional.
- [x] Remove the code to handle the 'json_data' request type from the Lambda function's front controller.
- [x] Deploy to operations and test again.

Option 2: Split up the messages on the server-side before passing them back through the websocket.  This would require changes in the server-side to: 1) Add message headers, including: unique message ID, size, sequence number, total number of parts; 2) split up the data and send multiple messages back to the client.  The client changes would need to include new code to: 1) Read and store partial messages; 2) Assemble the message parts into a full message; and 3) Process the message once the full message was received.  This could also be used to address issue #120.

**Comment by hahnd** [comment]
@fcvdb @fabiolrdiniz I emailed with Bill at AWS yesterday and we think that option 1 above will work:

> New PUTS have a read-after-write consistency model.  There is a caveat to that.  If you do a HEAD request on the object before it is created (before doing the PUT), then it’s an eventual consistency model like all other update/delete operations.

> I have not tested your exact situation but in testing I have done with CloudFront and S3 origins, I have seen objects be immediately available from CloudFront on creation.

I will update the issue description to include a check list of steps to accomplish this task.

**Comment by fcvdb** [comment]
@hahnd Are the last two action items done?

- [ ]  Remove the code to handle the 'json_data' request type from the Lambda function's front controller.
- [ ]  Deploy to operations and test again.

And we can close this issue?

**Comment by hahnd** [comment]
Yes, those are complete.  This issue can be closed.
