### ISSUE TITLE
Time series plots show all platforms (ignores selected platforms list)

### ISSUE THREAD

**Issue by hahnd** [JCSDA/FSOI#140]
## Description

The time series plots always show all platforms, even if only one platform is selected in the request.  The time series plots should only have lines for platforms that were selected in the request.  For the request linked below, I only selected radiosonde platform.  The time series plots still show all platforms.
http://ios.jcsda.org?cache_id=7CE2AED76A0FA7DF42AF945FD53B579E297566663A4858ACC8461CF335340B37

## Requirements

Time series plots should only show lines for platforms that were selected in the request.

## Acceptance Criteria (Definition of Done)

Time series plots should only show lines for platforms that were selected in the request.

## Dependencies

None.

**Comment by fcvdb** [comment]
This problem will be revisited in 2022 as  JCSDA's observations monitoring web applications are redeployed.
