### ISSUE TITLE
[Bug] The download_met tool is not retrieving all files from FTP when missing cases happen

### ISSUE THREAD

**Issue by fabiolrdiniz** [JCSDA/FSOI#156]
## Current behavior (describe the bug)
While transferring the UKMetOffice data in https://github.com/JCSDA-internal/FSOI/issues/156, an issue has been detected. The issue happens when one of the analysis cycles (00, 06, 12, 18Z) of a given day is not present in the FTP folder. If one cycle is missing, all the subsequent cycles for that day won't be transferred because the code exists with `550 Failed to open file`. This happens inside the following for loop:
https://github.com/JCSDA-internal/FSOI/blob/4586a683b6ca3b2b2af626d88b53708913cfe576/python/src/fsoi/ingest/met/download_met.py#L35-L50

## To Reproduce
Reproducible using develop.

## Expected behavior
Download all cycles for a given day.

**Comment by fcvdb** [comment]
This bug has been fixed.
