### ISSUE TITLE
Adding date information and manual axis range to plots in NRT site

### ISSUE THREAD

**Issue by BenjaminTJohnson** [JCSDA/FSOI#161]
## Description

The images that are generated as part of the ios.jcsda.org site do not have the date or date range for the given image.  Furthermore, the image filenames that are generated do not have dates, so if you saved these files they would over write each other.

My interest is in being able to create an animation of how impacts change over time at a given center, and the following elements would be useful

(1) Date ranges, analysis times, and agency on each figure

(2) Ability to set custom axis limits so that each image can have a  consistent range, making animation of a series of images more consistent.   

## Requirements

This would be an added feature, and would require some code changes to modify the title string and save string.    Adding a userbox for axis range might require more effort, but it would be beneficial for comparison purposes.

**Comment by fcvdb** [comment]
This feature will be added in the next [ios.jcsda.org](ios.jcsda.org) release in 2022.
