### ISSUE TITLE
Missing FSOI analysis cycles for NRL, GMAO, MET between Jan-2019 and Jul-2021

### ISSUE THREAD

**Issue by fabiolrdiniz** [JCSDA/FSOI#163]
Missing cycles were identified in the database between Jan-2019 and Jul-2021. Some of them are probably expected, but it's important to double-check them with the providers.

Since NRL and GMAO only provide 00Z data, we only checked for these analysis cycles. On the other hand, we checked for 00, 06, 12, and 18Z for MET because they provide FSOI data for all cycles.

A detailed list presenting the specific missing cycles is presented below for:
- NRL ([here](https://github.com/JCSDA-internal/FSOI/files/6935183/NRL.txt))
- GMAO ([here](https://github.com/JCSDA-internal/FSOI/files/6935181/GMAO.txt))
- MET ([here](https://github.com/JCSDA-internal/FSOI/files/6935182/MET.txt))

Notes:
1. For GMAO, only the `conv` file has been used to verify if a cycle is missing or not.
2. The missing analysis cycles during Mar-Jun 2021 are known for MET (see #149).

**Comment by fcvdb** [comment]
Missing data from 2019 and 2021 are not available anymore and won't be recovered.
