### ISSUE TITLE
Unknown Platform IDs

### ISSUE THREAD

**Issue by hahnd** [JCSDA/FSOI#90]
Determine the cause of unknown platform IDs in the most recent data: 
 - [x] UK Met (2018 Dec)
 - [x] NRL (real-time)
 - [x] GMAO (real-time)
 - [x] MERRA2 (2015-Jan and 2015-Jul)

**Comment by hahnd** [comment]
UKMet Unknown Platforms:
- FY-3B_MWHS-1
- FY-3C_MWHS-2
- FY-3C_MWHS-2 
- MT_SAPHIR

**Comment by hahnd** [comment]
NRL Unknown Platforms:
- Seviri

Seviri group into SEVIRI
http://ios.jcsda.org/?cache_id=937F6F1D4616E90EA959500AE7814071AC4A46821E266371F5B3D2AC54B677C3

**Comment by hahnd** [comment]
GMAO Unknown Platform IDs:
 - 247
 - 253

247 & 253 grouped into Geo_Wind
Before: http://ios.jcsda.org?cache_id=2A830BB861F01B82FBE1180BCA8CA683B24FAD1EEDB11D503EFE94349B7DA2B1
After: http://ios.jcsda.org?cache_id=1201A5D9D05E2225D3095E396E633C8A9A30C93266DC10F930E3A7305A952D2E

**Comment by fcvdb** [comment]
Platform IDs are stored in file FSOI/python/src/fsoi/platforms.yaml. Platforms for UK MetOffice files were addd. The file is now up to date.
